### ISSUE TITLE
Actividad 4. 

### ISSUE THREAD

**Issue by AmeliReyesHernandez** [SistemasTecTlaxiaco/actividad-4-mapa-mental-AmeliReyesHernandez#1]
![Comunicacion Oral y Escrita](https://user-images.githubusercontent.com/112219336/191611570-040fa99a-b0d3-437b-aab7-ec01ff1d0118.png)

**Comment by Blanca-estela-valerio-rivero** [comment]
Tiene un 18 de 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
